# Generated by Django 4.1.3 on 2022-12-06 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscore',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_core_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addresshome',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_home_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
