# Generated by Django 4.1.3 on 2022-11-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacation',
            unique_together=set(),
        ),
    ]
