# Generated by Django 4.1.3 on 2022-11-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pesel',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
