# Generated by Django 4.1.3 on 2022-11-29 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0002_alter_vacation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sending_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted_delegation'), ('rejected', 'rejected_delegation'), ('pending', 'pending_application')], max_length=16),
        ),
    ]
