# Generated by Django 4.1.3 on 2022-12-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0004_alter_messages_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_employees', 'can manage employees')]},
        ),
    ]
