# Generated by Django 4.1.3 on 2022-11-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0004_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted_vacation'), ('rejected', 'rejected_vacation'), ('pending', 'pending_application')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted_vacation'), ('rejected', 'rejected_vacation'), ('pending', 'pending_application')], max_length=10),
        ),
    ]
