# Generated by Django 4.1.3 on 2022-12-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0006_medicalleave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalleave',
            options={},
        ),
    ]
