# Generated by Django 4.1.3 on 2022-12-03 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_tool_app', '0009_alter_address_employee_alter_delegation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
